### ISSUE TITLE
Testing: View Private Resources

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/ViewPrivateResources#1]
The View Private Resources module allows Researcher and Author roles to view private resources. This is a very simple module, so testing should be straightforward. Install the module and the module configuration should provide two checkboxes:

- Allow researchers to view private resources
- Allow authors to view private resources

To test this module, make sure you first have a Researcher and Author account, and a private item, a private item set, and a private media. First, confirm that the Researcher and Author accounts can't view these resources. Then, as a global admin, check "Allow researchers to view private resources" and "Allow authors to view private resources." Confirm that the accounts can now view the resources.

**Comment by allanaaa** [comment]
Looks good to me: counts seem correct for items, media, and item sets.
